//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 12.0.21005.1
// 
namespace Riveu.Notifications.Windows8.NotificationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NotificationService.INotificationService")]
    public interface INotificationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationService/AuthenticateUser", ReplyAction="http://tempuri.org/INotificationService/AuthenticateUserResponse")]
        System.Threading.Tasks.Task<bool> AuthenticateUserAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationService/GetNotifications", ReplyAction="http://tempuri.org/INotificationService/GetNotificationsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<object>))]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<object>> GetNotificationsAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationService/RegisterSubscriber", ReplyAction="http://tempuri.org/INotificationService/RegisterSubscriberResponse")]
        System.Threading.Tasks.Task RegisterSubscriberAsync(string username, string password, string Uri, string deviceType, string deviceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationService/UnregisterSubscriber", ReplyAction="http://tempuri.org/INotificationService/UnregisterSubscriberResponse")]
        System.Threading.Tasks.Task UnregisterSubscriberAsync(string username, string password, string deviceType, string deviceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationService/SendNotification", ReplyAction="http://tempuri.org/INotificationService/SendNotificationResponse")]
        System.Threading.Tasks.Task SendNotificationAsync(string username, string password, string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INotificationServiceChannel : Riveu.Notifications.Windows8.NotificationService.INotificationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NotificationServiceClient : System.ServiceModel.ClientBase<Riveu.Notifications.Windows8.NotificationService.INotificationService>, Riveu.Notifications.Windows8.NotificationService.INotificationService {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public NotificationServiceClient() : 
                base(NotificationServiceClient.GetDefaultBinding(), NotificationServiceClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_INotificationService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NotificationServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(NotificationServiceClient.GetBindingForEndpoint(endpointConfiguration), NotificationServiceClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NotificationServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(NotificationServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NotificationServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(NotificationServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NotificationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<bool> AuthenticateUserAsync(string username, string password) {
            return base.Channel.AuthenticateUserAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<object>> GetNotificationsAsync(string username) {
            return base.Channel.GetNotificationsAsync(username);
        }
        
        public System.Threading.Tasks.Task RegisterSubscriberAsync(string username, string password, string Uri, string deviceType, string deviceId) {
            return base.Channel.RegisterSubscriberAsync(username, password, Uri, deviceType, deviceId);
        }
        
        public System.Threading.Tasks.Task UnregisterSubscriberAsync(string username, string password, string deviceType, string deviceId) {
            return base.Channel.UnregisterSubscriberAsync(username, password, deviceType, deviceId);
        }
        
        public System.Threading.Tasks.Task SendNotificationAsync(string username, string password, string message) {
            return base.Channel.SendNotificationAsync(username, password, message);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_INotificationService)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_INotificationService)) {
                return new System.ServiceModel.EndpointAddress("http://riveu.com/riveu/NotificationService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return NotificationServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_INotificationService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return NotificationServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_INotificationService);
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_INotificationService,
        }
    }
}
